<?php

/**
 * ContractstatusRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContractstatusRelationTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ContractstatusRelationTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ContractstatusRelation');
    }

    public static function formatData($array, $page) {
        $rows = ContractstatusTable::formatData(array(), 1, count($array));

        $pos = 0;
        foreach ($array as $row) {
            $contractstatus = ContractstatusTable::formatData(array($row->getToContractstatus()), 1, 1);

            $rows['data'][$pos] = $contractstatus['data'][0];

            $pos++;
        }

        $rows['metaData']['fields'] = array_merge($rows['metaData']['fields'], array(
            array('name' => 'fromstatus_id', 'type' => 'int'),
            array('name' => 'tostatus_id', 'type' => 'int'),
                ));


        return $rows;
    }

    public static function getAll($query, $distinct = false) {
        $q = Doctrine_Query::create()
                ->from('ContractstatusRelation cbr');

        if ($distinct) {
            $where = '';
            $params = array();
            for ($i = 0; $i < count($distinct); $i++) {
                if ($i == 0)
                    $where = $where . 'cbr.id != ?';
                else
                    $where = $where . ' AND cbr.id != ?';
                $params[] = $distinct[$i]->id;
            }
            $q->addWhere($where, $params);
        }

        if ($query && $query != '')
            $q = Doctrine_Query::create()
                    ->select('cbr.*')
                    ->from('ContractstatusRelation cbr')
                    ->where('cbr.fromstatus_id = ?', $query);

        return self::formatData($q->execute(), 1);
    }

}