<?php

/**
 * Location
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Location extends BaseLocation {

    public function getParentsAsArray($direction = "up") {
        $result = array();
        $parent = $this->getLocation();
        while ($parent && $parent->getId() > 0) {
            $result[] = $parent->toArray();
            $parent = $parent->getLocation();
        }

        if ($direction == "up")
            return $result;

        return array_reverse($result);
    }
	
    public function getParentsAsString($separator = " > ", $direction = "up") {
        $result = array($this->getName());

        $parent = $this->getLocation();
        while ($parent && $parent->getId() > 0) {
            $result[] = $parent->getName();
            $parent = $parent->getLocation();
        }

        if ($direction == "up")
            return implode($separator, $result);

        return implode($separator, array_reverse($result));
    }

}