<?php

/**
 * PersonPositionRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonPositionRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonPositionRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonPositionRelation');
    }
}