<?php

/**
 * Reclamationstatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reclamationstatus extends BaseReclamationstatus {

    public function isPrimary() {
        $q = Doctrine_Query::create()
                ->select('cbr.*')
                ->from('ReclamationstatusRelation cbr')
                ->where('cbr.tostatus_id = ?', $this->getId());
        if ($q->execute()->count() == 0)
            return true;
        return false;
    }

    public function isFinal() {
        if ($this->getReclamationStatues()->count() == 0)
            return true;
        return false;
    }

    public function isUsed() {
        if ($this->getReclamations()->count() > 0)
            return true;
        return false;
    }

    public function getAsArray() {
        $array = $this->toArray();
        $array['Calendar'] = $this->getCalendar()->toArray();

        return $array;
    }

    public function getName() {
        return $this->getCalendar()->getName();
    }

    public function getPercent() {
        $prestatues = Util::getArrayOrdered($this, array(), 'preorder', 'getReclamationstatus');
        $prev = count($prestatues)-1;
        
        $poststatues = Util::getArrayOrdered($this, array(), 'preorder', 'getReclamationStatues');
        $post = 0;
        foreach ($poststatues as $status) {
            $post++;
            if ($status['iscomplete'])
                break;
        }
        
        return $prev/($prev+$post-1)*100;
    }

}